
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital
    volumes: ['db_data:/var/lib/postgresql/data']
    ports: ['5432:5432']

  django:
    build: ./backend
    volumes: ['./backend:/code']
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hospital
    depends_on: ['db']
    ports: ['8000:8000']

  fastapi:
    build: ./prediction
    volumes: ['./prediction:/app']
    depends_on: ['db']
    ports: ['8001:8001']

  frontend:
    build: ./frontend
    volumes: ['./frontend:/app']
    ports: ['3000:3000']

volumes:
  db_data:
